<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
   <head>
    <meta charset="utf-8">
    <title>C.A.D</title>
    <link rel="stylesheet" href="estilo.css">
  </head>
  <body>
    <div class="menuPrincipal">
      <nav>
        <ul>
          <li><a href="index.html">>C.A.D</a></li>
          <li><a href="pagina01.html">O que é a depressão?</a></li>
        </ul>
      </nav>
    </div>
 
<div class="conteudo">
 <h1>O que é a depressão?</h1>
<p>
  A depressão é uma doença psiquiátrica que afeta o emocional da pessoa, que passa a apresentar tristeza profunda, falta de apetite, desânimo, pessimismo, baixa auto-estima, que aparecem com frequência e podem combinar-se entre si.

</p>
    <h2>O que é que causa depressão?</h2>
<p>Existem muitas possíveis causas da depressão, incluindo falta de regulação do humor pelo cérebro, vulnerabilidade genética, eventos estressantes da vida, medicamentos e problemas médicos.

</p>
    <h2>Como é o início de uma depressão?</h2>
<p>
  O início da depressão pode ser muito variado, dependendo da personalidade, temperamento, eventos que desencadeiam a doença, gênero e idade de cada pessoa. Os sinais frequentes mais comuns são: tristeza, falta de vontade, interesse e pensamento de ruína
</p>
    <h2>Como funciona a mente de uma pessoa com depressão?</h2>
<p>
  A diminuição da velocidade de raciocínio está entre os sintomas da depressão. Isso porque pessoas deprimidas ficam com o pensamento mais lento e demoram mais para entender algo. Em muitos casos, elas se perdem em suas próprias falas e ideias. A sensação é de que existe uma neblina mental atrapalhando seus pensamentos.
</p>
   <h2>Sintomas da depressão:</h2>
   <p>Além das alterações de humor ou irritabilidade, ansiedade e angústia a depressão possui diversos sinais e sintomas, que podem ser isolados ou somatizados. Os principais sintomas da depressão são:
   ° irritabilidade, ansiedade e angústia;
   ° desânimo, cansaço fácil, necessidade de maior esforço para fazer as coisas;
   ° diminuição ou incapacidade de sentir alegria e prazer ;
   ° desinteresse, falta de motivação e apatia;
   ° sentimentos de medo, insegurança, desesperança, desespero e desamparo;
   ° pessimismo, ideias frequentes e desproporcionais de culpa, baixa auto-estima;
   ° sensação, inutilidade, ruína e fracasso;
   ° interpretação distorcida e negativa da realidade;
   ° dificuldade de concentração, raciocínio mais lento e esquecimento;
   ° diminuição do desempenho sexual;
   ° perda ou aumento do apetite e do peso;
   ° insônia ou despertar matinal precoce;
   ° dores e outros sintomas físicos não justificados por problemas médicos; 
  </p>
<p>Muitas vezes dizem que a depressão é frescura mas cerca de 800 mil pessoas morrem por suicídio a cada ano - sendo essa a segunda principal causa de morte entre pessoas com idade entre 15 e 29 anos.No mudo cerca de uma pessoa a cada 40segundos morre por suicidio.</p>
<h2>O risco da depressão de acordo com um especialista:</h2>
<a href="https://youtu.be/09bRHdQvOcg"></a>
<a href="https://youtu.be/T2XLwjy65LA"></a>
     <div class="formacao">
        <img src="depressao2.jpg" alt="center">
      </div>
</div>




  </body>
</html>
